# Generated by Django 4.0.4 on 2022-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate1',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rate2',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.TextField(default=0),
        ),
    ]
